import { Router } from 'express';
import { healthRouter } from './health.route';
import { authRouter } from './auth.route';
import { medicineRouter } from './medicine.route';
import { inventoryRouter } from './inventory.route';
import { salesRouter } from './sales.route';
import { customerRouter } from './customer.route';
import { supplierRouter } from './supplier.route';
import { purchaseRouter } from './purchase.route';
import { prescriptionRouter } from './prescription.route';
import { returnRouter } from './return.route';
import { expenseRouter } from './expense.route';
import { reportRouter } from './report.route';
import { employeeRouter } from './employee.route';
import { settingsRouter } from './settings.route';
import { heldSaleRouter } from './heldSale.route';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/medicines', medicineRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/sales', salesRouter);
apiRouter.use('/customers', customerRouter);
apiRouter.use('/suppliers', supplierRouter);
apiRouter.use('/purchases', purchaseRouter);
apiRouter.use('/prescriptions', prescriptionRouter);
apiRouter.use('/returns', returnRouter);
apiRouter.use('/expenses', expenseRouter);
apiRouter.use('/reports', reportRouter);
apiRouter.use('/employees', employeeRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/held-sales', heldSaleRouter);
